version: "3"

services:
  localstack:
    image: docker.pkg.github.com/bishtawi/s3fs/localstack:${DOCKER_TAG:-test}
    build: ./docker/localstack
    restart: unless-stopped
    ports:
      - 4572:4572
    environment:
      START_WEB: 0
