version: "3"

services:
  localstack:
    image: docker.pkg.github.com/bishtawi/s3fs/localstack:${DOCKER_TAG:-latest}
    build: ./docker/localstack
    restart: unless-stopped
    ports:
      - 4572:4572
    environment:
      START_WEB: 0
  ## Instead of pulling my private docker image which already has the files preloaded into the mock s3 bucket at build time,
  ## we can also use the official localstack image and then volume mount the init script to load the files into the mock s3 at run-time
  # localstack-official:
  #   image: localstack/localstack:latest
  #   restart: unless-stopped
  #   ports:
  #     - 4572:4572
  #   environment:
  #     SERVICES: s3:4572
  #     START_WEB: 0
  #   volumes:
  #     - ./docker/localstack:/docker-entrypoint-initaws.d/
  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: insecure-password
